### ISSUE TITLE
ShadowDOM Copy Button Failure

### ISSUE THREAD

**Issue by brandonam** [Inflectra/ui-test-automation-playground#10]
Unfortunately it seems there is a runtime error when clicking the copy button in this sandbox and nothing is being copied to the clipboard regardless if the user clicks the generate guid button.

`shadowdom:45`      
```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at GuidGenerator.buttonCopy.onclick (shadowdom:45:33)
```

Steps to reproduce:

1. Navigate to http://uitestingplayground.com/shadowdom
2. Click the copy button
3. Observe the console log

**Comment by awarecan** [comment]
Clipboard function only available in HTTPS secure context in Chrome. Please try to use https://uitestingplayground.com/shadowdom

**Comment by brandonam** [comment]
Thank you for the update. This now works as per your suggestion.

**Comment by ngraf** [comment]
@awarecan , Is it expected that the certificate is considered insecure?

![image](https://user-images.githubusercontent.com/7094389/229855419-8da8cf16-e754-4a36-88cd-c04d5875338e.png)

![image](https://user-images.githubusercontent.com/7094389/229855382-ffea3004-a86c-42f5-9cbc-eb88997956ca.png)

I really would like to write a test automation for the Shadow DOM scenario. So far I ran all other tests in HTTP, but for Shadow DOM feature this is not possible.
